/** Auto-generated by scripts/generate-batch4-media.mjs — do not edit manually */

export type MediaItem = {
  id: string;
  name: string;
  displayName: string;
  credit?: string;
  path: string;
  type: 'pdf' | 'image' | 'link' | 'file' | 'duas_gallery';
  url?: string;
  classTags?: string[];
  description?: string;
};

export type MediaSection = {
  id: string;
  name: string;
  defaultCollapsed?: boolean;
  items?: MediaItem[];
  children?: { id: string; name: string; items: MediaItem[] }[];
};

export const batch4MediaTree: MediaSection[] = [
  {
    "id": "official",
    "name": "Official Notes & Books",
    "items": [
      {
        "id": "Classmate_Notes_Official_notes_or_Book_pdfs_Qasasun_Nabiyyeen_1_4_pdf",
        "name": "Qasasun.Nabiyyeen_1-4.pdf",
        "displayName": "Qasasun.Nabiyyeen 1-4",
        "path": "/batch4/Classmate_Notes/Official_notes_or_Book_pdfs/Qasasun.Nabiyyeen_1-4.pdf",
        "type": "pdf"
      },
      {
        "id": "Classmate_Notes_Official_notes_or_Book_pdfs_Safwa_tul_Masaadir_Arabic_English_pdf",
        "name": "Safwa-tul-Masaadir-Arabic-English.pdf",
        "displayName": "Safwa-tul-Masaadir-Arabic-English",
        "path": "/batch4/Classmate_Notes/Official_notes_or_Book_pdfs/Safwa-tul-Masaadir-Arabic-English.pdf",
        "type": "pdf"
      },
      {
        "id": "Classmate_Notes_Official_notes_or_Book_pdfs_SimpleFiqhTranslationOfAl_fiqhUlMuyassar_pdf",
        "name": "SimpleFiqhTranslationOfAl-fiqhUlMuyassar.pdf",
        "displayName": "SimpleFiqhTranslationOfAl-fiqhUlMuyassar",
        "path": "/batch4/Classmate_Notes/Official_notes_or_Book_pdfs/SimpleFiqhTranslationOfAl-fiqhUlMuyassar.pdf",
        "type": "pdf"
      },
      {
        "id": "Classmate_Notes_Official_notes_or_Book_pdfs_The_Money_Handbook_pdf",
        "name": "The Money Handbook.pdf",
        "displayName": "The Money Handbook",
        "path": "/batch4/Classmate_Notes/Official_notes_or_Book_pdfs/The%20Money%20Handbook.pdf",
        "type": "pdf"
      },
      {
        "id": "Classmate_Notes_Official_notes_or_Book_pdfs_Arabic_Nahw_First_Semester_Sh_Hunzla_pdf",
        "name": "Arabic_Nahw_First_Semester (Sh. Hunzla).pdf",
        "displayName": "Arabic Nahw First Semester",
        "credit": "Sh. Hunzla",
        "path": "https://drive.google.com/file/d/1dpzJ0MYfm2FtHvSvaD7d2f2tEOQdw3eo/view?usp=sharing",
        "type": "link",
        "url": "https://drive.google.com/file/d/1dpzJ0MYfm2FtHvSvaD7d2f2tEOQdw3eo/view?usp=sharing"
      },
      {
        "id": "Classmate_Notes_Official_notes_or_Book_pdfs_40_Rabbana_Duas_From_the_Quran_pdf",
        "name": "40 Rabbana Duas From the Quran.pdf",
        "displayName": "40 Rabbana Duas From the Quran",
        "path": "/batch4/Classmate_Notes/Official_notes_or_Book_pdfs/40%20Rabbana%20Duas%20From%20the%20Quran.pdf",
        "type": "pdf"
      },
      {
        "id": "Classmate_Notes_Official_notes_or_Book_pdfs_Arabic_201_2024_Miftaah_pdf",
        "name": "Arabic 201_2024 (Miftaah).pdf",
        "displayName": "Arabic 201 2024",
        "credit": "Miftaah",
        "path": "/batch4/Classmate_Notes/Official_notes_or_Book_pdfs/Arabic%20201_2024%20(Miftaah).pdf",
        "type": "pdf"
      },
      {
        "id": "Classmate_Notes_Official_notes_or_Book_pdfs_Arabic_Stories_for_Language_Learners_Sh_Hunzla_pdf",
        "name": "Arabic Stories for Language Learners (Sh. Hunzla).pdf",
        "displayName": "Arabic Stories for Language Learners",
        "credit": "Sh. Hunzla",
        "path": "/batch4/Classmate_Notes/Official_notes_or_Book_pdfs/Arabic%20Stories%20for%20Language%20Learners%20(Sh.%20Hunzla).pdf",
        "type": "pdf"
      },
      {
        "id": "Classmate_Notes_Official_notes_or_Book_pdfs_Morning_Adhkaar_Amanah_Fitness_pdf",
        "name": "Morning Adhkaar Amanah Fitness.pdf",
        "displayName": "Morning Adhkaar",
        "path": "/batch4/Classmate_Notes/Official_notes_or_Book_pdfs/Morning%20Adhkaar%20Amanah%20Fitness.pdf",
        "type": "pdf"
      },
      {
        "id": "Classmate_Notes_Official_notes_or_Book_pdfs_Salaah_differences_Men_and_Women_MAW_pdf",
        "name": "Salaah differences Men and Women (MAW).pdf",
        "displayName": "Salaah differences Men and Women",
        "credit": "MAW",
        "path": "/batch4/Classmate_Notes/Official_notes_or_Book_pdfs/Salaah%20differences%20Men%20and%20Women%20(MAW).pdf",
        "type": "pdf"
      },
      {
        "id": "Classmate_Notes_Official_notes_or_Book_pdfs_The_Essential_Guide_to_Arabic_Vocabulary_Miftaah_pdf",
        "name": "The Essential Guide to Arabic Vocabulary - Miftaah.pdf",
        "displayName": "The Essential Guide to Arabic Vocabulary - Miftaah",
        "path": "/batch4/Classmate_Notes/Official_notes_or_Book_pdfs/The%20Essential%20Guide%20to%20Arabic%20Vocabulary%20-%20Miftaah.pdf",
        "type": "pdf"
      },
      {
        "id": "Classmate_Notes_Official_notes_or_Book_pdfs_inner_dimensions_of_islamic_worship_muhtar_Al_Ghazali_pdf",
        "name": "inner-dimensions-of-islamic-worship-muhtar (Al-Ghazali).pdf",
        "displayName": "inner-dimensions-of-islamic-worship-muhtar",
        "credit": "Al-Ghazali",
        "path": "/batch4/Classmate_Notes/Official_notes_or_Book_pdfs/inner-dimensions-of-islamic-worship-muhtar%20(Al-Ghazali).pdf",
        "type": "pdf"
      },
      {
        "id": "Classmate_Notes_Official_notes_or_Book_pdfs_safa7at_pdf",
        "name": "safa7at.pdf",
        "displayName": "safa7at",
        "path": "/batch4/Classmate_Notes/Official_notes_or_Book_pdfs/safa7at.pdf",
        "type": "pdf"
      },
      {
        "id": "Classmate_Notes_Official_notes_or_Book_pdfs_pdf",
        "name": "‎أحوال الموتى.pdf",
        "displayName": "‎أحوال الموتى",
        "path": "/batch4/Classmate_Notes/Official_notes_or_Book_pdfs/%E2%80%8E%D8%A7%D9%94%D8%AD%D9%88%D8%A7%D9%84%20%D8%A7%D9%84%D9%85%D9%88%D8%AA%D9%89.pdf",
        "type": "pdf"
      }
    ]
  },
  {
    "id": "comprehensive",
    "name": "Student Notes",
    "children": [
      {
        "id": "comp_seerah",
        "name": "Seerah",
        "items": [
          {
            "id": "Classmate_Notes_Comprehensive_Notes_Seekers_Notes_2025_Aman_pdf",
            "name": "Seekers Notes 2025 (Aman).pdf",
            "displayName": "Military Expeditions",
            "credit": "Aman",
            "path": "/batch4/Classmate_Notes/Comprehensive_Notes/Seekers%20Notes%202025%20(Aman).pdf",
            "type": "pdf",
            "classTags": [
              "Seerah"
            ]
          },
          {
            "id": "Classmate_Notes_Comprehensive_Notes_Seerah_2_Amayra_pdf",
            "name": "Seerah 2(Amayra).pdf",
            "displayName": "Seerah 2",
            "credit": "Amayra",
            "path": "/batch4/Classmate_Notes/Comprehensive_Notes/Seerah%202(Amayra).pdf",
            "type": "pdf",
            "classTags": [
              "Seerah"
            ]
          },
          {
            "id": "Classmate_Notes_Comprehensive_Notes_Seerah_pt_4_Amayra_pdf",
            "name": "Seerah pt. 4 (Amayra).pdf",
            "displayName": "Seerah pt. 4",
            "credit": "Amayra",
            "path": "/batch4/Classmate_Notes/Comprehensive_Notes/Seerah%20pt.%204%20(Amayra).pdf",
            "type": "pdf",
            "classTags": [
              "Seerah"
            ]
          }
        ]
      },
      {
        "id": "comp_fiqh",
        "name": "Fiqh",
        "items": [
          {
            "id": "Classmate_Notes_Comprehensive_Notes_Fiqh_of_Fasting_Amayra_pdf",
            "name": "Fiqh of Fasting (Amayra).pdf",
            "displayName": "Fiqh of Fasting",
            "credit": "Amayra",
            "path": "/batch4/Classmate_Notes/Comprehensive_Notes/Fiqh%20of%20Fasting%20(Amayra).pdf",
            "type": "pdf",
            "classTags": [
              "Fiqh"
            ]
          },
          {
            "id": "Classmate_Notes_Comprehensive_Notes_Fiqh_of_Fasting_and_Sadaqah_Fitr_Noor_pdf",
            "name": "Fiqh of Fasting and Sadaqah Fitr (Noor).pdf",
            "displayName": "Fiqh of Fasting and Sadaqah Fitr",
            "credit": "Noor",
            "path": "/batch4/Classmate_Notes/Comprehensive_Notes/Fiqh%20of%20Fasting%20and%20Sadaqah%20Fitr%20(Noor).pdf",
            "type": "pdf",
            "classTags": [
              "Fiqh"
            ]
          },
          {
            "id": "Classmate_Notes_Comprehensive_Notes_Fiqh_of_Fasting_Summarized_Yasmine_pdf",
            "name": "Fiqh of Fasting Summarized (Yasmine) .pdf",
            "displayName": "Fiqh of Fasting Summarized",
            "path": "/batch4/Classmate_Notes/Comprehensive_Notes/Fiqh%20of%20Fasting%20Summarized%20(Yasmine)%20.pdf",
            "type": "pdf",
            "classTags": [
              "Fiqh"
            ]
          },
          {
            "id": "Classmate_Notes_Comprehensive_Notes_Fiqh_of_Finance_Summarized_Yasmine_pdf",
            "name": "Fiqh of Finance Summarized (Yasmine).pdf",
            "displayName": "Fiqh of Finance Summarized",
            "credit": "Yasmine",
            "path": "/batch4/Classmate_Notes/Comprehensive_Notes/Fiqh%20of%20Finance%20Summarized%20(Yasmine).pdf",
            "type": "pdf",
            "classTags": [
              "Fiqh"
            ]
          },
          {
            "id": "Classmate_Notes_Comprehensive_Notes_Fiqh_of_Zakaat_Summarized_Yasmine_pdf",
            "name": "Fiqh of Zakaat Summarized (Yasmine).pdf",
            "displayName": "Fiqh of Zakaat Summarized",
            "credit": "Yasmine",
            "path": "/batch4/Classmate_Notes/Comprehensive_Notes/Fiqh%20of%20Zakaat%20Summarized%20(Yasmine).pdf",
            "type": "pdf",
            "classTags": [
              "Fiqh"
            ]
          }
        ]
      },
      {
        "id": "comp_uloom_hadith",
        "name": "Uloom Hadith",
        "items": [
          {
            "id": "Classmate_Notes_Comprehensive_Notes_Hadith_Terminology_Uloom_Al_Hadith_Aqsa_pdf",
            "name": "Hadith Terminology - Uloom Al Hadith (Aqsa).pdf",
            "displayName": "Hadith Terminology - Uloom Al Hadith",
            "credit": "Aqsa",
            "path": "/batch4/Classmate_Notes/Comprehensive_Notes/Hadith%20Terminology%20-%20Uloom%20Al%20Hadith%20(Aqsa).pdf",
            "type": "pdf",
            "classTags": [
              "Uloom Hadith"
            ]
          },
          {
            "id": "Classmate_Notes_Comprehensive_Notes_Hadith_Types_Yasmine_JPG",
            "name": "Hadith_Types (Yasmine).JPG",
            "displayName": "Hadith Types",
            "credit": "Yasmine",
            "path": "/batch4/Classmate_Notes/Comprehensive_Notes/Hadith_Types%20(Yasmine).JPG",
            "type": "image",
            "classTags": [
              "Uloom Hadith"
            ]
          },
          {
            "id": "Classmate_Notes_Comprehensive_Notes_Sahih_Sittah_Uloom_Hadith_Amayra_JPG",
            "name": "Sahih_Sittah_Uloom_Hadith (Amayra).JPG",
            "displayName": "Sahih Sittah Uloom Hadith",
            "credit": "Amayra",
            "path": "/batch4/Classmate_Notes/Comprehensive_Notes/Sahih_Sittah_Uloom_Hadith%20(Amayra).JPG",
            "type": "image",
            "classTags": [
              "Uloom Hadith"
            ]
          },
          {
            "id": "Classmate_Notes_Comprehensive_Notes_Uloom_Al_Hadith_Amayra_pdf",
            "name": "Uloom Al Hadith (Amayra).pdf",
            "displayName": "Uloom Al Hadith",
            "credit": "Amayra",
            "path": "/batch4/Classmate_Notes/Comprehensive_Notes/Uloom%20Al%20Hadith%20(Amayra).pdf",
            "type": "pdf",
            "classTags": [
              "Uloom Hadith"
            ]
          },
          {
            "id": "Classmate_Notes_Comprehensive_Notes_Uloom_Al_Hadith_Flowchart_lejla_pdf",
            "name": "Uloom Al- Hadith Flowchart (lejla).pdf",
            "displayName": "Uloom Al- Hadith Flowchart",
            "credit": "lejla",
            "path": "https://drive.google.com/file/d/1VQlhXqBzZXeAWvCKSdID1Z-D-Lw9G58W/view?usp=sharing",
            "type": "link",
            "url": "https://drive.google.com/file/d/1VQlhXqBzZXeAWvCKSdID1Z-D-Lw9G58W/view?usp=sharing",
            "classTags": [
              "Uloom Hadith"
            ]
          }
        ]
      },
      {
        "id": "comp_tafsir_juz_amma",
        "name": "Tafsir Juz Amma",
        "items": [
          {
            "id": "Classmate_Notes_Comprehensive_Notes_Study_Guide_Juz_Amma_Aqsa_pdf",
            "name": "📖 Study Guide – Juz ʿAmma - (Aqsa).pdf",
            "displayName": "📖 Study Guide – Juz ʿAmma -",
            "credit": "Aqsa",
            "path": "/batch4/Classmate_Notes/Comprehensive_Notes/%F0%9F%93%96%20Study%20Guide%20%E2%80%93%20Juz%20%CA%BFAmma%20-%20(Aqsa).pdf",
            "type": "pdf",
            "classTags": [
              "Tafsir Juz Amma"
            ]
          },
          {
            "id": "Classmate_Notes_Comprehensive_Notes_Ayat_Breakdown_Diagrams_Juz_Amma_Surahs_93_104_Amayra_pdf",
            "name": "Ayat Breakdown Diagrams - Juz Amma Surahs 93-104 (Amayra).pdf",
            "displayName": "Ayat Breakdown Diagrams - Juz Amma Surahs 93-104",
            "credit": "Amayra",
            "path": "/batch4/Classmate_Notes/Comprehensive_Notes/Ayat%20Breakdown%20Diagrams%20-%20Juz%20Amma%20Surahs%2093-104%20(Amayra).pdf",
            "type": "pdf",
            "classTags": [
              "Tafsir Juz Amma"
            ]
          },
          {
            "id": "Classmate_Notes_Comprehensive_Notes_Surah_Baqarah_Tarjumaa_Rule_Book_Sumaya_pdf",
            "name": "Surah Baqarah Tarjumaa Rule Book (Sumaya).pdf",
            "displayName": "Surah Baqarah Tarjumaa Rule Book",
            "credit": "Sumaya",
            "path": "/batch4/Classmate_Notes/Comprehensive_Notes/Surah%20Baqarah%20Tarjumaa%20Rule%20Book%20(Sumaya).pdf",
            "type": "pdf",
            "classTags": [
              "Tafsir Juz Amma"
            ]
          },
          {
            "id": "Classmate_Notes_Comprehensive_Notes_Tafseer_of_Juz_Amma_Asr_till_Duha_MAW_Yasmine_pdf",
            "name": "Tafseer of Juz Amma - Asr till Duha - MAW (Yasmine).pdf",
            "displayName": "Tafseer of Juz Amma - Asr till Duha - MAW",
            "credit": "Yasmine",
            "path": "/batch4/Classmate_Notes/Comprehensive_Notes/Tafseer%20of%20Juz%20Amma%20-%20Asr%20till%20Duha%20-%20MAW%20(Yasmine).pdf",
            "type": "pdf",
            "classTags": [
              "Tafsir Juz Amma"
            ]
          },
          {
            "id": "Classmate_Notes_Comprehensive_Notes_Tafseer_of_Juz_Amma_Last_10_Surahs_MAW_Noor_Mansoor_pdf",
            "name": "Tafseer of Juz Amma - Last 10 Surahs - MAW (Noor Mansoor).pdf",
            "displayName": "Tafseer of Juz Amma - Last 10 Surahs - MAW",
            "credit": "Noor Mansoor",
            "path": "/batch4/Classmate_Notes/Comprehensive_Notes/Tafseer%20of%20Juz%20Amma%20-%20Last%2010%20Surahs%20-%20MAW%20(Noor%20Mansoor).pdf",
            "type": "pdf",
            "classTags": [
              "Tafsir Juz Amma"
            ]
          },
          {
            "id": "Classmate_Notes_Comprehensive_Notes_Tafsir_of_Juz_Amma_Asr_till_Duha_MAW_pt_2_Amayra_pdf",
            "name": "Tafsir of Juz Amma - Asr till Duha- MAW pt. 2  (Amayra).pdf",
            "displayName": "Tafsir of Juz Amma - Asr till Duha- MAW pt. 2",
            "credit": "Amayra",
            "path": "/batch4/Classmate_Notes/Comprehensive_Notes/Tafsir%20of%20Juz%20Amma%20-%20Asr%20till%20Duha-%20MAW%20pt.%202%20%20(Amayra).pdf",
            "type": "pdf",
            "classTags": [
              "Tafsir Juz Amma"
            ]
          },
          {
            "id": "Classmate_Notes_Comprehensive_Notes_Tafsir_of_Juz_Amma_Last_10_Surahs_MAW_Amayra_pdf",
            "name": "Tafsir of Juz Amma - Last 10 Surahs - MAW (Amayra).pdf",
            "displayName": "Tafsir of Juz Amma - Last 10 Surahs - MAW",
            "credit": "Amayra",
            "path": "/batch4/Classmate_Notes/Comprehensive_Notes/Tafsir%20of%20Juz%20Amma%20-%20Last%2010%20Surahs%20-%20MAW%20(Amayra).pdf",
            "type": "pdf",
            "classTags": [
              "Tafsir Juz Amma"
            ]
          },
          {
            "id": "Classmate_Notes_Comprehensive_Notes_Tafsir_of_Juz_Amma_1st_Half_Sheikh_Abdullah_Amayra_pdf",
            "name": "Tafsir of Juz Amma 1st Half - Sheikh Abdullah (Amayra).pdf",
            "displayName": "Tafsir of Juz Amma 1st Half - Sheikh Abdullah",
            "credit": "Amayra",
            "path": "/batch4/Classmate_Notes/Comprehensive_Notes/Tafsir%20of%20Juz%20Amma%201st%20Half%20-%20Sheikh%20Abdullah%20(Amayra).pdf",
            "type": "pdf",
            "classTags": [
              "Tafsir Juz Amma"
            ]
          }
        ]
      },
      {
        "id": "comp_surah_yusuf",
        "name": "Surah Yusuf",
        "items": [
          {
            "id": "Classmate_Notes_Comprehensive_Notes_Surah_Yusuf_Overview_Aqsa_pdf",
            "name": "Surah Yusuf Overview(Aqsa).pdf",
            "displayName": "Surah Yusuf Overview",
            "credit": "Aqsa",
            "path": "/batch4/Classmate_Notes/Comprehensive_Notes/Surah%20Yusuf%20Overview(Aqsa).pdf",
            "type": "pdf",
            "classTags": [
              "Surah Yusuf"
            ]
          },
          {
            "id": "Classmate_Notes_Comprehensive_Notes_Surah_Yusuf_Question_Answers_Amayra_pdf",
            "name": "Surah Yusuf Question   Answers (Amayra) .pdf",
            "displayName": "Surah Yusuf Question   Answers",
            "path": "/batch4/Classmate_Notes/Comprehensive_Notes/Surah%20Yusuf%20Question%20%20%20Answers%20(Amayra)%20.pdf",
            "type": "pdf",
            "classTags": [
              "Surah Yusuf"
            ]
          }
        ]
      },
      {
        "id": "comp_tazkiyyah",
        "name": "Tazkiyyah",
        "items": [
          {
            "id": "Classmate_Notes_Comprehensive_Notes_Aqeedah_Amayra_pdf",
            "name": "Aqeedah (Amayra).pdf",
            "displayName": "Aqeedah",
            "credit": "Amayra",
            "path": "/batch4/Classmate_Notes/Comprehensive_Notes/Aqeedah%20(Amayra).pdf",
            "type": "pdf",
            "classTags": [
              "Tazkiyyah"
            ]
          }
        ]
      }
    ]
  },
  {
    "id": "arabic_guides",
    "name": "Arabic Guides",
    "items": [
      {
        "id": "Classmate_Notes_Arabic_Guides_Arabic_scales_Nadine_JPG",
        "name": "Arabic_scales (Nadine).JPG",
        "displayName": "Arabic scales",
        "credit": "Nadine",
        "path": "/batch4/Classmate_Notes/Arabic_Guides/Arabic_scales%20(Nadine).JPG",
        "type": "image",
        "classTags": [
          "Arabic"
        ]
      },
      {
        "id": "Classmate_Notes_Arabic_Guides_Arabic_scales_2_Nadine_JPG",
        "name": "Arabic_scales_2 (Nadine).JPG",
        "displayName": "Arabic scales 2",
        "credit": "Nadine",
        "path": "/batch4/Classmate_Notes/Arabic_Guides/Arabic_scales_2%20(Nadine).JPG",
        "type": "image",
        "classTags": [
          "Arabic"
        ]
      },
      {
        "id": "Classmate_Notes_Arabic_Guides_Beginner_Vocabulary_Sh_Hunzla_JPG",
        "name": "Beginner Vocabulary (Sh. Hunzla).JPG",
        "displayName": "Beginner Vocabulary",
        "credit": "Sh. Hunzla",
        "path": "/batch4/Classmate_Notes/Arabic_Guides/Beginner%20Vocabulary%20(Sh.%20Hunzla).JPG",
        "type": "image",
        "classTags": [
          "Arabic"
        ]
      },
      {
        "id": "Classmate_Notes_Arabic_Guides_Beginner_Vocabulary_2_Sh_Hunzla_JPG",
        "name": "Beginner Vocabulary 2 (Sh.Hunzla).JPG",
        "displayName": "Beginner Vocabulary 2",
        "credit": "Sh.Hunzla",
        "path": "/batch4/Classmate_Notes/Arabic_Guides/Beginner%20Vocabulary%202%20(Sh.Hunzla).JPG",
        "type": "image",
        "classTags": [
          "Arabic"
        ]
      },
      {
        "id": "Classmate_Notes_Arabic_Guides_Flowchart_of_Nuruddin_JPG",
        "name": "Flowchart of اِلَّا (Nuruddin).JPG",
        "displayName": "Flowchart of اِلَّا",
        "credit": "Nuruddin",
        "path": "/batch4/Classmate_Notes/Arabic_Guides/Flowchart%20of%20%D8%A7%D9%90%D9%84%D9%8E%D9%91%D8%A7%20(Nuruddin).JPG",
        "type": "image",
        "classTags": [
          "Arabic"
        ]
      },
      {
        "id": "Classmate_Notes_Arabic_Guides_Huroof_Naasiba_wa_Jaazima_JPG",
        "name": "Huroof_Naasiba_wa_Jaazima.JPG",
        "displayName": "Huroof Naasiba wa Jaazima",
        "path": "/batch4/Classmate_Notes/Arabic_Guides/Huroof_Naasiba_wa_Jaazima.JPG",
        "type": "image",
        "classTags": [
          "Arabic"
        ]
      },
      {
        "id": "Classmate_Notes_Arabic_Guides_Ism_Mustaq_Yasmine_JPG",
        "name": "Ism_Mustaq (Yasmine).JPG",
        "displayName": "Ism Mustaq",
        "credit": "Yasmine",
        "path": "/batch4/Classmate_Notes/Arabic_Guides/Ism_Mustaq%20(Yasmine).JPG",
        "type": "image",
        "classTags": [
          "Arabic"
        ]
      },
      {
        "id": "Classmate_Notes_Arabic_Guides_Masculine_and_Feminine_Noun_identification_JPG",
        "name": "Masculine_and_Feminine_Noun_identification.JPG",
        "displayName": "Masculine and Feminine Noun identification",
        "path": "/batch4/Classmate_Notes/Arabic_Guides/Masculine_and_Feminine_Noun_identification.JPG",
        "type": "image",
        "classTags": [
          "Arabic"
        ]
      },
      {
        "id": "Classmate_Notes_Arabic_Guides_Masdar_into_Verb_Equivalent_Conversion_Amayra_JPG",
        "name": "Masdar into Verb Equivalent Conversion(Amayra).JPG",
        "displayName": "Masdar into Verb Equivalent Conversion",
        "credit": "Amayra",
        "path": "/batch4/Classmate_Notes/Arabic_Guides/Masdar%20into%20Verb%20Equivalent%20Conversion(Amayra).JPG",
        "type": "image",
        "classTags": [
          "Arabic"
        ]
      },
      {
        "id": "Classmate_Notes_Arabic_Guides_Naasiba_7_12_Nadine_JPG",
        "name": "Naasiba_7-12 (Nadine).JPG",
        "displayName": "Naasiba 7-12",
        "credit": "Nadine",
        "path": "/batch4/Classmate_Notes/Arabic_Guides/Naasiba_7-12%20(Nadine).JPG",
        "type": "image",
        "classTags": [
          "Arabic"
        ]
      },
      {
        "id": "Classmate_Notes_Arabic_Guides_Naasibah_1_6_pt1_Nadine_JPG",
        "name": "Naasibah_1-6_pt1 (Nadine).JPG",
        "displayName": "Naasibah 1-6 pt1",
        "credit": "Nadine",
        "path": "/batch4/Classmate_Notes/Arabic_Guides/Naasibah_1-6_pt1%20(Nadine).JPG",
        "type": "image",
        "classTags": [
          "Arabic"
        ]
      },
      {
        "id": "Classmate_Notes_Arabic_Guides_Seekers_Verbs_with_Present_Tense_Sh_Hunzla_pdf",
        "name": "Seekers Verbs (with Present Tense) (Sh. Hunzla).pdf",
        "displayName": "Seekers Verbs (with Present Tense)",
        "credit": "Sh. Hunzla",
        "path": "/batch4/Classmate_Notes/Arabic_Guides/Seekers%20Verbs%20(with%20Present%20Tense)%20(Sh.%20Hunzla).pdf",
        "type": "pdf",
        "classTags": [
          "Arabic"
        ]
      },
      {
        "id": "Classmate_Notes_Arabic_Guides_Seekers_Vocab_Past_Present_Sifaat_Sh_Hunzla_pdf",
        "name": "Seekers Vocab Past-Present-Sifaat (Sh. Hunzla).pdf",
        "displayName": "Seekers Vocab Past:Present:Sifaat",
        "credit": "Sh. Hunzla",
        "path": "/batch4/Classmate_Notes/Arabic_Guides/Seekers%20Vocab%20Past-Present-Sifaat%20(Sh.%20Hunzla).pdf",
        "type": "pdf",
        "classTags": [
          "Arabic"
        ]
      },
      {
        "id": "Classmate_Notes_Arabic_Guides_Status_of_flowchart_Amayra_JPG",
        "name": "Status of اِلَّا flowchart (Amayra).JPG",
        "displayName": "Status of اِلَّا flowchart",
        "credit": "Amayra",
        "path": "/batch4/Classmate_Notes/Arabic_Guides/Status%20of%20%D8%A7%D9%90%D9%84%D9%8E%D9%91%D8%A7%20flowchart%20(Amayra).JPG",
        "type": "image",
        "classTags": [
          "Arabic"
        ]
      },
      {
        "id": "Classmate_Notes_Arabic_Guides_Verb_Conversion_to_Ann_Maa_Masdariyya_Amayra_JPG",
        "name": "Verb Conversion to Ann-Maa Masdariyya (Amayra).JPG",
        "displayName": "Verb Conversion to Ann-Maa Masdariyya",
        "credit": "Amayra",
        "path": "/batch4/Classmate_Notes/Arabic_Guides/Verb%20Conversion%20to%20Ann-Maa%20Masdariyya%20(Amayra).JPG",
        "type": "image",
        "classTags": [
          "Arabic"
        ]
      },
      {
        "id": "link_50_Sentence_Generator_Arhum_",
        "name": "Sentence Generator (Arhum)",
        "displayName": "Sentence Generator",
        "credit": "Arhum",
        "path": "https://chatgpt.com/g/g-68fa247cbe988191b5da9c3de3dedfc3-arabic-sentence-generator-miftaah-seekers",
        "type": "link",
        "url": "https://chatgpt.com/g/g-68fa247cbe988191b5da9c3de3dedfc3-arabic-sentence-generator-miftaah-seekers",
        "classTags": [
          "Arabic"
        ]
      },
      {
        "id": "link_51_Sarf_Word_Practice_Generator",
        "name": "Sarf Word Practice Generator",
        "displayName": "Sarf Word Practice Generator",
        "path": "https://sarfing.app",
        "type": "link",
        "url": "https://sarfing.app",
        "classTags": [
          "Arabic"
        ]
      }
    ]
  },
  {
    "id": "quizlets",
    "name": "Quizlets",
    "items": [
      {
        "id": "link_100_Arabic_Vocabulary_Quizlet_Miski_",
        "name": "Arabic Vocabulary Quizlet (Miski)",
        "displayName": "Arabic Vocabulary Quizlet",
        "credit": "Miski",
        "path": "https://quizlet.com/1077642316/arabic-vocabulary-flash-cards/?i=3s0dgi&x=1jqY",
        "type": "link",
        "url": "https://quizlet.com/1077642316/arabic-vocabulary-flash-cards/?i=3s0dgi&x=1jqY",
        "classTags": []
      },
      {
        "id": "link_101_Arabic_Sarf_Vocab_Set_Sarf_Part_2_Arhum_",
        "name": "Arabic Sarf Vocab Set - Sarf Part 2 (Arhum)",
        "displayName": "Arabic Sarf Vocab Set - Sarf Part 2",
        "credit": "Arhum",
        "path": "https://quizlet.com/1070870221/vocab-set-2-sarf-section-flash-cards/?i=6qeu4n&x=1jqY",
        "type": "link",
        "url": "https://quizlet.com/1070870221/vocab-set-2-sarf-section-flash-cards/?i=6qeu4n&x=1jqY",
        "classTags": []
      },
      {
        "id": "link_102_Arabic_Sarf_Vocab_Set_Sarf_Part_2",
        "name": "Arabic Sarf Vocab Set - Sarf Part 2",
        "displayName": "Arabic Sarf Vocab Set - Sarf Part 2",
        "path": "https://quizlet.com/1095134612/sarf-vocab-set-1-flash-cards/?i=6saqto&x=1jqY",
        "type": "link",
        "url": "https://quizlet.com/1095134612/sarf-vocab-set-1-flash-cards/?i=6saqto&x=1jqY",
        "classTags": []
      },
      {
        "id": "link_103_Quizlet_for_Uloom_Hadith_Terminology_Aqsa_",
        "name": "Quizlet for Uloom Hadith Terminology (Aqsa)",
        "displayName": "Quizlet for Uloom Hadith Terminology",
        "credit": "Aqsa",
        "path": "https://quizlet.com/845936651/uloom-al-hadith-flash-cards/?i=5zwu9x&x=1jqY",
        "type": "link",
        "url": "https://quizlet.com/845936651/uloom-al-hadith-flash-cards/?i=5zwu9x&x=1jqY",
        "classTags": []
      },
      {
        "id": "link_104_Canva_Flashcards_for_Uloom_Al_Hadith_Yasmine_",
        "name": "Canva Flashcards for Uloom Al-Hadith (Yasmine)",
        "displayName": "Canva Flashcards for Uloom Al-Hadith",
        "credit": "Yasmine",
        "path": "https://www.canva.com/design/DAG68OVEdNg/K6ABExtWiP3ifWQcRCTxJg/view?utm_content=DAG68OVEdNg&utm_campaign=designshare&utm_medium=link2&utm_source=uniquelinks&utlId=ha289dd50a3#1",
        "type": "link",
        "url": "https://www.canva.com/design/DAG68OVEdNg/K6ABExtWiP3ifWQcRCTxJg/view?utm_content=DAG68OVEdNg&utm_campaign=designshare&utm_medium=link2&utm_source=uniquelinks&utlId=ha289dd50a3#1",
        "classTags": []
      }
    ]
  },
  {
    "id": "duas",
    "name": "Duas from Seerah",
    "items": [
      {
        "id": "Classmate_Notes_Duas_from_Seerah_05bf0398_22fd_4095_8a63_adcc81bcd5e8_JPG",
        "name": "05bf0398-22fd-4095-8a63-adcc81bcd5e8.JPG",
        "displayName": "05bf0398-22fd-4095-8a63-adcc81bcd5e8",
        "path": "/batch4/Classmate_Notes/Duas_from_Seerah/05bf0398-22fd-4095-8a63-adcc81bcd5e8.JPG",
        "type": "image",
        "classTags": [
          "Seerah"
        ],
        "description": ""
      },
      {
        "id": "Classmate_Notes_Duas_from_Seerah_085c73c4_f0bc_486b_b894_2ca8f3dd5008_JPG",
        "name": "085c73c4-f0bc-486b-b894-2ca8f3dd5008.JPG",
        "displayName": "085c73c4-f0bc-486b-b894-2ca8f3dd5008",
        "path": "/batch4/Classmate_Notes/Duas_from_Seerah/085c73c4-f0bc-486b-b894-2ca8f3dd5008.JPG",
        "type": "image",
        "classTags": [
          "Seerah"
        ],
        "description": ""
      },
      {
        "id": "Classmate_Notes_Duas_from_Seerah_164dd666_1d27_4ee5_8518_2e005db702f9_JPG",
        "name": "164dd666-1d27-4ee5-8518-2e005db702f9.JPG",
        "displayName": "164dd666-1d27-4ee5-8518-2e005db702f9",
        "path": "/batch4/Classmate_Notes/Duas_from_Seerah/164dd666-1d27-4ee5-8518-2e005db702f9.JPG",
        "type": "image",
        "classTags": [
          "Seerah"
        ],
        "description": ""
      },
      {
        "id": "Classmate_Notes_Duas_from_Seerah_1a41c972_dc73_438f_99b6_afc2cffa3b08_JPG",
        "name": "1a41c972-dc73-438f-99b6-afc2cffa3b08.JPG",
        "displayName": "1a41c972-dc73-438f-99b6-afc2cffa3b08",
        "path": "/batch4/Classmate_Notes/Duas_from_Seerah/1a41c972-dc73-438f-99b6-afc2cffa3b08.JPG",
        "type": "image",
        "classTags": [
          "Seerah"
        ],
        "description": ""
      },
      {
        "id": "Classmate_Notes_Duas_from_Seerah_1b948a14_69dd_4b06_b9cd_b30d53445fb6_JPG",
        "name": "1b948a14-69dd-4b06-b9cd-b30d53445fb6.JPG",
        "displayName": "1b948a14-69dd-4b06-b9cd-b30d53445fb6",
        "path": "/batch4/Classmate_Notes/Duas_from_Seerah/1b948a14-69dd-4b06-b9cd-b30d53445fb6.JPG",
        "type": "image",
        "classTags": [
          "Seerah"
        ],
        "description": ""
      },
      {
        "id": "Classmate_Notes_Duas_from_Seerah_1f729938_9547_462d_9fd7_62e83d098cf2_JPG",
        "name": "1f729938-9547-462d-9fd7-62e83d098cf2.JPG",
        "displayName": "1f729938-9547-462d-9fd7-62e83d098cf2",
        "path": "/batch4/Classmate_Notes/Duas_from_Seerah/1f729938-9547-462d-9fd7-62e83d098cf2.JPG",
        "type": "image",
        "classTags": [
          "Seerah"
        ],
        "description": ""
      },
      {
        "id": "Classmate_Notes_Duas_from_Seerah_28c00f15_66bd_4368_b145_fb496a28b7be_JPG",
        "name": "28c00f15-66bd-4368-b145-fb496a28b7be.JPG",
        "displayName": "28c00f15-66bd-4368-b145-fb496a28b7be",
        "path": "/batch4/Classmate_Notes/Duas_from_Seerah/28c00f15-66bd-4368-b145-fb496a28b7be.JPG",
        "type": "image",
        "classTags": [
          "Seerah"
        ],
        "description": ""
      },
      {
        "id": "Classmate_Notes_Duas_from_Seerah_320c080d_87a2_4e8a_8fcb_9ebf352db0d8_JPG",
        "name": "320c080d-87a2-4e8a-8fcb-9ebf352db0d8.JPG",
        "displayName": "320c080d-87a2-4e8a-8fcb-9ebf352db0d8",
        "path": "/batch4/Classmate_Notes/Duas_from_Seerah/320c080d-87a2-4e8a-8fcb-9ebf352db0d8.JPG",
        "type": "image",
        "classTags": [
          "Seerah"
        ],
        "description": ""
      },
      {
        "id": "Classmate_Notes_Duas_from_Seerah_3a6129fa_4860_440f_bbd7_79545c2b2c9a_JPG",
        "name": "3a6129fa-4860-440f-bbd7-79545c2b2c9a.JPG",
        "displayName": "3a6129fa-4860-440f-bbd7-79545c2b2c9a",
        "path": "/batch4/Classmate_Notes/Duas_from_Seerah/3a6129fa-4860-440f-bbd7-79545c2b2c9a.JPG",
        "type": "image",
        "classTags": [
          "Seerah"
        ],
        "description": ""
      },
      {
        "id": "Classmate_Notes_Duas_from_Seerah_56d1255d_94b9_4e87_b052_255b03b30485_JPG",
        "name": "56d1255d-94b9-4e87-b052-255b03b30485.JPG",
        "displayName": "56d1255d-94b9-4e87-b052-255b03b30485",
        "path": "/batch4/Classmate_Notes/Duas_from_Seerah/56d1255d-94b9-4e87-b052-255b03b30485.JPG",
        "type": "image",
        "classTags": [
          "Seerah"
        ],
        "description": ""
      },
      {
        "id": "Classmate_Notes_Duas_from_Seerah_63082ef7_b216_4414_b686_ebaefb4d4f13_JPG",
        "name": "63082ef7-b216-4414-b686-ebaefb4d4f13.JPG",
        "displayName": "63082ef7-b216-4414-b686-ebaefb4d4f13",
        "path": "/batch4/Classmate_Notes/Duas_from_Seerah/63082ef7-b216-4414-b686-ebaefb4d4f13.JPG",
        "type": "image",
        "classTags": [
          "Seerah"
        ],
        "description": ""
      },
      {
        "id": "Classmate_Notes_Duas_from_Seerah_6c4b9777_2785_41fa_8ff0_4b021bd20029_JPG",
        "name": "6c4b9777-2785-41fa-8ff0-4b021bd20029.JPG",
        "displayName": "6c4b9777-2785-41fa-8ff0-4b021bd20029",
        "path": "/batch4/Classmate_Notes/Duas_from_Seerah/6c4b9777-2785-41fa-8ff0-4b021bd20029.JPG",
        "type": "image",
        "classTags": [
          "Seerah"
        ],
        "description": ""
      },
      {
        "id": "Classmate_Notes_Duas_from_Seerah_6cc94753_2259_4b52_93ff_dc276dade014_JPG",
        "name": "6cc94753-2259-4b52-93ff-dc276dade014.JPG",
        "displayName": "6cc94753-2259-4b52-93ff-dc276dade014",
        "path": "/batch4/Classmate_Notes/Duas_from_Seerah/6cc94753-2259-4b52-93ff-dc276dade014.JPG",
        "type": "image",
        "classTags": [
          "Seerah"
        ],
        "description": ""
      },
      {
        "id": "Classmate_Notes_Duas_from_Seerah_7639db8a_56cd_4053_9cad_e997ca7ddcd9_JPG",
        "name": "7639db8a-56cd-4053-9cad-e997ca7ddcd9.JPG",
        "displayName": "7639db8a-56cd-4053-9cad-e997ca7ddcd9",
        "path": "/batch4/Classmate_Notes/Duas_from_Seerah/7639db8a-56cd-4053-9cad-e997ca7ddcd9.JPG",
        "type": "image",
        "classTags": [
          "Seerah"
        ],
        "description": ""
      },
      {
        "id": "Classmate_Notes_Duas_from_Seerah_7c760e20_ec70_414e_b24f_e6471051322e_JPG",
        "name": "7c760e20-ec70-414e-b24f-e6471051322e.JPG",
        "displayName": "7c760e20-ec70-414e-b24f-e6471051322e",
        "path": "/batch4/Classmate_Notes/Duas_from_Seerah/7c760e20-ec70-414e-b24f-e6471051322e.JPG",
        "type": "image",
        "classTags": [
          "Seerah"
        ],
        "description": ""
      },
      {
        "id": "Classmate_Notes_Duas_from_Seerah_80fec1c5_a533_4a83_ae5f_a013b1881b7f_JPG",
        "name": "80fec1c5-a533-4a83-ae5f-a013b1881b7f.JPG",
        "displayName": "80fec1c5-a533-4a83-ae5f-a013b1881b7f",
        "path": "/batch4/Classmate_Notes/Duas_from_Seerah/80fec1c5-a533-4a83-ae5f-a013b1881b7f.JPG",
        "type": "image",
        "classTags": [
          "Seerah"
        ],
        "description": ""
      },
      {
        "id": "Classmate_Notes_Duas_from_Seerah_Dua_for_Wudhu_pdf",
        "name": "Dua_for_Wudhu.pdf",
        "displayName": "Dua for Wudhu",
        "path": "/batch4/Classmate_Notes/Duas_from_Seerah/Dua_for_Wudhu.pdf",
        "type": "pdf",
        "classTags": [
          "Seerah"
        ],
        "description": ""
      },
      {
        "id": "Classmate_Notes_Duas_from_Seerah_Dua_for_clear_vision_JPG",
        "name": "Dua_for_clear_vision.JPG",
        "displayName": "Dua for clear vision",
        "path": "/batch4/Classmate_Notes/Duas_from_Seerah/Dua_for_clear_vision.JPG",
        "type": "image",
        "classTags": [
          "Seerah"
        ],
        "description": ""
      },
      {
        "id": "Classmate_Notes_Duas_from_Seerah_aa54f3c1_691e_44a3_b8a2_ce1d10426d84_JPG",
        "name": "aa54f3c1-691e-44a3-b8a2-ce1d10426d84.JPG",
        "displayName": "aa54f3c1-691e-44a3-b8a2-ce1d10426d84",
        "path": "/batch4/Classmate_Notes/Duas_from_Seerah/aa54f3c1-691e-44a3-b8a2-ce1d10426d84.JPG",
        "type": "image",
        "classTags": [
          "Seerah"
        ],
        "description": ""
      },
      {
        "id": "Classmate_Notes_Duas_from_Seerah_b3aa548d_44e6_4ec6_95d8_788755e747cd_JPG",
        "name": "b3aa548d-44e6-4ec6-95d8-788755e747cd.JPG",
        "displayName": "b3aa548d-44e6-4ec6-95d8-788755e747cd",
        "path": "/batch4/Classmate_Notes/Duas_from_Seerah/b3aa548d-44e6-4ec6-95d8-788755e747cd.JPG",
        "type": "image",
        "classTags": [
          "Seerah"
        ],
        "description": ""
      },
      {
        "id": "Classmate_Notes_Duas_from_Seerah_c199ff46_ace9_4a89_812c_f7c0bfdc8ee3_JPG",
        "name": "c199ff46-ace9-4a89-812c-f7c0bfdc8ee3.JPG",
        "displayName": "c199ff46-ace9-4a89-812c-f7c0bfdc8ee3",
        "path": "/batch4/Classmate_Notes/Duas_from_Seerah/c199ff46-ace9-4a89-812c-f7c0bfdc8ee3.JPG",
        "type": "image",
        "classTags": [
          "Seerah"
        ],
        "description": ""
      },
      {
        "id": "Classmate_Notes_Duas_from_Seerah_c908ee85_ebe6_4b61_b1ee_f3ba9f4cc294_JPG",
        "name": "c908ee85-ebe6-4b61-b1ee-f3ba9f4cc294.JPG",
        "displayName": "c908ee85-ebe6-4b61-b1ee-f3ba9f4cc294",
        "path": "/batch4/Classmate_Notes/Duas_from_Seerah/c908ee85-ebe6-4b61-b1ee-f3ba9f4cc294.JPG",
        "type": "image",
        "classTags": [
          "Seerah"
        ],
        "description": ""
      },
      {
        "id": "Classmate_Notes_Duas_from_Seerah_ccc2a7ea_092f_4a70_8640_9760c0b2cf7d_JPG",
        "name": "ccc2a7ea-092f-4a70-8640-9760c0b2cf7d.JPG",
        "displayName": "ccc2a7ea-092f-4a70-8640-9760c0b2cf7d",
        "path": "/batch4/Classmate_Notes/Duas_from_Seerah/ccc2a7ea-092f-4a70-8640-9760c0b2cf7d.JPG",
        "type": "image",
        "classTags": [
          "Seerah"
        ],
        "description": ""
      },
      {
        "id": "Classmate_Notes_Duas_from_Seerah_d28356ad_3f5b_4546_b08c_a8aebab7931f_JPG",
        "name": "d28356ad-3f5b-4546-b08c-a8aebab7931f.JPG",
        "displayName": "d28356ad-3f5b-4546-b08c-a8aebab7931f",
        "path": "/batch4/Classmate_Notes/Duas_from_Seerah/d28356ad-3f5b-4546-b08c-a8aebab7931f.JPG",
        "type": "image",
        "classTags": [
          "Seerah"
        ],
        "description": ""
      },
      {
        "id": "Classmate_Notes_Duas_from_Seerah_d6374068_27db_48fc_8163_18aeb9fa9ccd_JPG",
        "name": "d6374068-27db-48fc-8163-18aeb9fa9ccd.JPG",
        "displayName": "d6374068-27db-48fc-8163-18aeb9fa9ccd",
        "path": "/batch4/Classmate_Notes/Duas_from_Seerah/d6374068-27db-48fc-8163-18aeb9fa9ccd.JPG",
        "type": "image",
        "classTags": [
          "Seerah"
        ],
        "description": ""
      },
      {
        "id": "Classmate_Notes_Duas_from_Seerah_e7fc09ca_ba9f_4e2b_950e_800cc41f3e7f_JPG",
        "name": "e7fc09ca-ba9f-4e2b-950e-800cc41f3e7f.JPG",
        "displayName": "e7fc09ca-ba9f-4e2b-950e-800cc41f3e7f",
        "path": "/batch4/Classmate_Notes/Duas_from_Seerah/e7fc09ca-ba9f-4e2b-950e-800cc41f3e7f.JPG",
        "type": "image",
        "classTags": [
          "Seerah"
        ],
        "description": ""
      },
      {
        "id": "Classmate_Notes_Duas_from_Seerah_f29a0671_1507_425a_8ec8_ae5b9b347165_JPG",
        "name": "f29a0671-1507-425a-8ec8-ae5b9b347165.JPG",
        "displayName": "f29a0671-1507-425a-8ec8-ae5b9b347165",
        "path": "/batch4/Classmate_Notes/Duas_from_Seerah/f29a0671-1507-425a-8ec8-ae5b9b347165.JPG",
        "type": "image",
        "classTags": [
          "Seerah"
        ],
        "description": ""
      },
      {
        "id": "Classmate_Notes_Duas_from_Seerah_f6874a1a_f2d9_4010_b118_5ac7859fb50f_JPG",
        "name": "f6874a1a-f2d9-4010-b118-5ac7859fb50f.JPG",
        "displayName": "f6874a1a-f2d9-4010-b118-5ac7859fb50f",
        "path": "/batch4/Classmate_Notes/Duas_from_Seerah/f6874a1a-f2d9-4010-b118-5ac7859fb50f.JPG",
        "type": "image",
        "classTags": [
          "Seerah"
        ],
        "description": ""
      }
    ]
  },
  {
    "id": "seerah_diagrams",
    "name": "Seerah Diagrams",
    "items": [
      {
        "id": "Classmate_Notes_Seerah_Diagrams_Abu_Bakr_s_Expeditions_Post_Death_of_Prophet_SA_JPG",
        "name": "Abu-Bakr's Expeditions Post-Death of Prophet SA.JPG",
        "displayName": "Abu-Bakr's Expeditions Post-Death of Prophet SA",
        "path": "/batch4/Classmate_Notes/Seerah_Diagrams/Abu-Bakr's%20Expeditions%20Post-Death%20of%20Prophet%20SA.JPG",
        "type": "image",
        "classTags": [
          "Seerah"
        ]
      },
      {
        "id": "Classmate_Notes_Seerah_Diagrams_Hajj_breakdown_JPG",
        "name": "Hajj_breakdown.JPG",
        "displayName": "Hajj breakdown",
        "path": "/batch4/Classmate_Notes/Seerah_Diagrams/Hajj_breakdown.JPG",
        "type": "image",
        "classTags": [
          "Seerah"
        ]
      },
      {
        "id": "Classmate_Notes_Seerah_Diagrams_Hajj_breakdown_2_JPG",
        "name": "Hajj_breakdown_2.JPG",
        "displayName": "Hajj breakdown 2",
        "path": "/batch4/Classmate_Notes/Seerah_Diagrams/Hajj_breakdown_2.JPG",
        "type": "image",
        "classTags": [
          "Seerah"
        ]
      },
      {
        "id": "Classmate_Notes_Seerah_Diagrams_Khaybar_Rotations_JPG",
        "name": "Khaybar_Rotations.JPG",
        "displayName": "Khaybar Rotations",
        "path": "/batch4/Classmate_Notes/Seerah_Diagrams/Khaybar_Rotations.JPG",
        "type": "image",
        "classTags": [
          "Seerah"
        ]
      },
      {
        "id": "Classmate_Notes_Seerah_Diagrams_Map_of_peninsula_JPG",
        "name": "Map_of_peninsula.JPG",
        "displayName": "Map of peninsula",
        "path": "/batch4/Classmate_Notes/Seerah_Diagrams/Map_of_peninsula.JPG",
        "type": "image",
        "classTags": [
          "Seerah"
        ]
      }
    ]
  },
  {
    "id": "arabic_practice",
    "name": "Arabic Practice",
    "defaultCollapsed": true,
    "items": [
      {
        "id": "Classmate_Notes_Worksheets_and_templates_Arabic_Practice_025c2d7f_fe18_4f87_b903_4d3af35ab775_JPG",
        "name": "025c2d7f-fe18-4f87-b903-4d3af35ab775.JPG",
        "displayName": "025c2d7f-fe18-4f87-b903-4d3af35ab775",
        "path": "/batch4/Classmate_Notes/Worksheets_and_templates/Arabic_Practice/025c2d7f-fe18-4f87-b903-4d3af35ab775.JPG",
        "type": "image",
        "classTags": [
          "Arabic"
        ]
      },
      {
        "id": "Classmate_Notes_Worksheets_and_templates_Arabic_Practice_0624d4ed_5647_4104_a423_6acf3cab3d5f_JPG",
        "name": "0624d4ed-5647-4104-a423-6acf3cab3d5f.JPG",
        "displayName": "0624d4ed-5647-4104-a423-6acf3cab3d5f",
        "path": "/batch4/Classmate_Notes/Worksheets_and_templates/Arabic_Practice/0624d4ed-5647-4104-a423-6acf3cab3d5f.JPG",
        "type": "image",
        "classTags": [
          "Arabic"
        ]
      },
      {
        "id": "Classmate_Notes_Worksheets_and_templates_Arabic_Practice_15240e1f_23a6_4cf8_a1e3_8b1595dfc2da_JPG",
        "name": "15240e1f-23a6-4cf8-a1e3-8b1595dfc2da.JPG",
        "displayName": "15240e1f-23a6-4cf8-a1e3-8b1595dfc2da",
        "path": "/batch4/Classmate_Notes/Worksheets_and_templates/Arabic_Practice/15240e1f-23a6-4cf8-a1e3-8b1595dfc2da.JPG",
        "type": "image",
        "classTags": [
          "Arabic"
        ]
      },
      {
        "id": "Classmate_Notes_Worksheets_and_templates_Arabic_Practice_2cb01dce_164f_46ad_bb37_beb8147a7217_JPG",
        "name": "2cb01dce-164f-46ad-bb37-beb8147a7217.JPG",
        "displayName": "2cb01dce-164f-46ad-bb37-beb8147a7217",
        "path": "/batch4/Classmate_Notes/Worksheets_and_templates/Arabic_Practice/2cb01dce-164f-46ad-bb37-beb8147a7217.JPG",
        "type": "image",
        "classTags": [
          "Arabic"
        ]
      },
      {
        "id": "Classmate_Notes_Worksheets_and_templates_Arabic_Practice_402740ec_2b94_46e6_8dcc_a0f2ba2e7966_JPG",
        "name": "402740ec-2b94-46e6-8dcc-a0f2ba2e7966.JPG",
        "displayName": "402740ec-2b94-46e6-8dcc-a0f2ba2e7966",
        "path": "/batch4/Classmate_Notes/Worksheets_and_templates/Arabic_Practice/402740ec-2b94-46e6-8dcc-a0f2ba2e7966.JPG",
        "type": "image",
        "classTags": [
          "Arabic"
        ]
      },
      {
        "id": "Classmate_Notes_Worksheets_and_templates_Arabic_Practice_493c2959_cde7_47a0_9f7a_6654130b49e5_JPG",
        "name": "493c2959-cde7-47a0-9f7a-6654130b49e5.JPG",
        "displayName": "493c2959-cde7-47a0-9f7a-6654130b49e5",
        "path": "/batch4/Classmate_Notes/Worksheets_and_templates/Arabic_Practice/493c2959-cde7-47a0-9f7a-6654130b49e5.JPG",
        "type": "image",
        "classTags": [
          "Arabic"
        ]
      },
      {
        "id": "Classmate_Notes_Worksheets_and_templates_Arabic_Practice_495b67b4_2693_40a1_9b2c_62a2811694ac_JPG",
        "name": "495b67b4-2693-40a1-9b2c-62a2811694ac.JPG",
        "displayName": "495b67b4-2693-40a1-9b2c-62a2811694ac",
        "path": "/batch4/Classmate_Notes/Worksheets_and_templates/Arabic_Practice/495b67b4-2693-40a1-9b2c-62a2811694ac.JPG",
        "type": "image",
        "classTags": [
          "Arabic"
        ]
      },
      {
        "id": "Classmate_Notes_Worksheets_and_templates_Arabic_Practice_4d504fed_e70a_4d10_80a5_7e888c87fcf3_JPG",
        "name": "4d504fed-e70a-4d10-80a5-7e888c87fcf3.JPG",
        "displayName": "4d504fed-e70a-4d10-80a5-7e888c87fcf3",
        "path": "/batch4/Classmate_Notes/Worksheets_and_templates/Arabic_Practice/4d504fed-e70a-4d10-80a5-7e888c87fcf3.JPG",
        "type": "image",
        "classTags": [
          "Arabic"
        ]
      },
      {
        "id": "Classmate_Notes_Worksheets_and_templates_Arabic_Practice_4fa13ec9_a2f3_40f3_8255_10351c666ba3_JPG",
        "name": "4fa13ec9-a2f3-40f3-8255-10351c666ba3.JPG",
        "displayName": "4fa13ec9-a2f3-40f3-8255-10351c666ba3",
        "path": "/batch4/Classmate_Notes/Worksheets_and_templates/Arabic_Practice/4fa13ec9-a2f3-40f3-8255-10351c666ba3.JPG",
        "type": "image",
        "classTags": [
          "Arabic"
        ]
      },
      {
        "id": "Classmate_Notes_Worksheets_and_templates_Arabic_Practice_5a28baa2_1dd2_4992_b1b9_73cce10df3cd_JPG",
        "name": "5a28baa2-1dd2-4992-b1b9-73cce10df3cd.JPG",
        "displayName": "5a28baa2-1dd2-4992-b1b9-73cce10df3cd",
        "path": "/batch4/Classmate_Notes/Worksheets_and_templates/Arabic_Practice/5a28baa2-1dd2-4992-b1b9-73cce10df3cd.JPG",
        "type": "image",
        "classTags": [
          "Arabic"
        ]
      },
      {
        "id": "Classmate_Notes_Worksheets_and_templates_Arabic_Practice_6b15ce62_ea14_43f0_b101_323532bf00c9_JPG",
        "name": "6b15ce62-ea14-43f0-b101-323532bf00c9.JPG",
        "displayName": "6b15ce62-ea14-43f0-b101-323532bf00c9",
        "path": "/batch4/Classmate_Notes/Worksheets_and_templates/Arabic_Practice/6b15ce62-ea14-43f0-b101-323532bf00c9.JPG",
        "type": "image",
        "classTags": [
          "Arabic"
        ]
      },
      {
        "id": "Classmate_Notes_Worksheets_and_templates_Arabic_Practice_6ce7170b_bc05_43e9_9710_50c08f1a722f_JPG",
        "name": "6ce7170b-bc05-43e9-9710-50c08f1a722f.JPG",
        "displayName": "6ce7170b-bc05-43e9-9710-50c08f1a722f",
        "path": "/batch4/Classmate_Notes/Worksheets_and_templates/Arabic_Practice/6ce7170b-bc05-43e9-9710-50c08f1a722f.JPG",
        "type": "image",
        "classTags": [
          "Arabic"
        ]
      },
      {
        "id": "Classmate_Notes_Worksheets_and_templates_Arabic_Practice_7b4a67dd_cac9_4d10_9922_0756e02def34_JPG",
        "name": "7b4a67dd-cac9-4d10-9922-0756e02def34.JPG",
        "displayName": "7b4a67dd-cac9-4d10-9922-0756e02def34",
        "path": "/batch4/Classmate_Notes/Worksheets_and_templates/Arabic_Practice/7b4a67dd-cac9-4d10-9922-0756e02def34.JPG",
        "type": "image",
        "classTags": [
          "Arabic"
        ]
      },
      {
        "id": "Classmate_Notes_Worksheets_and_templates_Arabic_Practice_a14e1626_9c7c_4948_9043_38b87a9f2094_JPG",
        "name": "a14e1626-9c7c-4948-9043-38b87a9f2094.JPG",
        "displayName": "a14e1626-9c7c-4948-9043-38b87a9f2094",
        "path": "/batch4/Classmate_Notes/Worksheets_and_templates/Arabic_Practice/a14e1626-9c7c-4948-9043-38b87a9f2094.JPG",
        "type": "image",
        "classTags": [
          "Arabic"
        ]
      },
      {
        "id": "Classmate_Notes_Worksheets_and_templates_Arabic_Practice_bc7becba_df61_4fa3_853a_6ea43ce7e443_JPG",
        "name": "bc7becba-df61-4fa3-853a-6ea43ce7e443.JPG",
        "displayName": "bc7becba-df61-4fa3-853a-6ea43ce7e443",
        "path": "/batch4/Classmate_Notes/Worksheets_and_templates/Arabic_Practice/bc7becba-df61-4fa3-853a-6ea43ce7e443.JPG",
        "type": "image",
        "classTags": [
          "Arabic"
        ]
      },
      {
        "id": "Classmate_Notes_Worksheets_and_templates_Arabic_Practice_e0f3a0c1_b172_44ac_90a6_b8febc8d7e8c_JPG",
        "name": "e0f3a0c1-b172-44ac-90a6-b8febc8d7e8c.JPG",
        "displayName": "e0f3a0c1-b172-44ac-90a6-b8febc8d7e8c",
        "path": "/batch4/Classmate_Notes/Worksheets_and_templates/Arabic_Practice/e0f3a0c1-b172-44ac-90a6-b8febc8d7e8c.JPG",
        "type": "image",
        "classTags": [
          "Arabic"
        ]
      },
      {
        "id": "Classmate_Notes_Worksheets_and_templates_Arabic_Practice_e79d9f13_5c8b_4e9e_ac92_c2f7d0e40b94_JPG",
        "name": "e79d9f13-5c8b-4e9e-ac92-c2f7d0e40b94.JPG",
        "displayName": "e79d9f13-5c8b-4e9e-ac92-c2f7d0e40b94",
        "path": "/batch4/Classmate_Notes/Worksheets_and_templates/Arabic_Practice/e79d9f13-5c8b-4e9e-ac92-c2f7d0e40b94.JPG",
        "type": "image",
        "classTags": [
          "Arabic"
        ]
      },
      {
        "id": "Classmate_Notes_Worksheets_and_templates_Arabic_Practice_f8167da4_8dcf_4be8_b590_4476fe7ba275_JPG",
        "name": "f8167da4-8dcf-4be8-b590-4476fe7ba275.JPG",
        "displayName": "f8167da4-8dcf-4be8-b590-4476fe7ba275",
        "path": "/batch4/Classmate_Notes/Worksheets_and_templates/Arabic_Practice/f8167da4-8dcf-4be8-b590-4476fe7ba275.JPG",
        "type": "image",
        "classTags": [
          "Arabic"
        ]
      },
      {
        "id": "Classmate_Notes_Worksheets_and_templates_Arabic_Practice_First_Year_Badl_Worksheet_Sh_Hunzla_pdf",
        "name": "First Year Badl Worksheet (Sh. Hunzla).pdf",
        "displayName": "First Year Badl Worksheet",
        "credit": "Sh. Hunzla",
        "path": "/batch4/Classmate_Notes/Worksheets_and_templates/Arabic_Practice/First%20Year%20Badl%20Worksheet%20(Sh.%20Hunzla).pdf",
        "type": "pdf",
        "classTags": [
          "Arabic"
        ]
      },
      {
        "id": "Classmate_Notes_Worksheets_and_templates_Arabic_Practice_First_Year_Ta_keed_Practice_Sh_Hunzla_pdf",
        "name": "First Year Ta'keed Practice (Sh. Hunzla).pdf",
        "displayName": "First Year Ta'keed Practice",
        "credit": "Sh. Hunzla",
        "path": "/batch4/Classmate_Notes/Worksheets_and_templates/Arabic_Practice/First%20Year%20Ta'keed%20Practice%20(Sh.%20Hunzla).pdf",
        "type": "pdf",
        "classTags": [
          "Arabic"
        ]
      }
    ]
  },
  {
    "id": "recordings",
    "name": "Recordings & References",
    "defaultCollapsed": true,
    "items": [
      {
        "id": "link_200_Early_Quran_Manuscripts",
        "name": "Early Quran Manuscripts",
        "displayName": "Early Quran Manuscripts",
        "path": "https://corpuscoranicum.de/en/verse-navigator/sura/20/verse/1/manuscripts",
        "type": "link",
        "url": "https://corpuscoranicum.de/en/verse-navigator/sura/20/verse/1/manuscripts",
        "classTags": []
      },
      {
        "id": "link_201_Expansion_Chronology_of_Masjid_Nabawi",
        "name": "Expansion Chronology of Masjid Nabawi",
        "displayName": "Expansion Chronology of Masjid Nabawi",
        "path": "https://madainproject.com/expansion_chronology_of_masjid_al_nabawi",
        "type": "link",
        "url": "https://madainproject.com/expansion_chronology_of_masjid_al_nabawi",
        "classTags": []
      },
      {
        "id": "link_202_Quranic_verses_on_Taqwa",
        "name": "Quranic verses on Taqwa",
        "displayName": "Quranic verses on Taqwa",
        "path": "https://myislam.org/quran-verses/taqwa/",
        "type": "link",
        "url": "https://myislam.org/quran-verses/taqwa/",
        "classTags": []
      },
      {
        "id": "link_203_Mufti_Aasim_Path_of_the_Seekers_pt_1",
        "name": "Mufti Aasim: Path of the Seekers pt 1",
        "displayName": "Mufti Aasim: Path of the Seekers pt 1",
        "path": "https://youtu.be/uSbTwQD9UNI",
        "type": "link",
        "url": "https://youtu.be/uSbTwQD9UNI",
        "classTags": []
      },
      {
        "id": "link_204_Mufti_Aasim_Path_of_the_Seekers_pt2",
        "name": "Mufti Aasim: Path of the Seekers pt2",
        "displayName": "Mufti Aasim: Path of the Seekers pt2",
        "path": "https://youtu.be/Bt3608s6FbU",
        "type": "link",
        "url": "https://youtu.be/Bt3608s6FbU",
        "classTags": []
      },
      {
        "id": "link_205_Minaret_of_Isa_Umayyid_Mosque",
        "name": "Minaret of Isa - Umayyid Mosque",
        "displayName": "Minaret of Isa - Umayyid Mosque",
        "path": "https://madainproject.com/minaret_of_isa_(umayyad_mosque)",
        "type": "link",
        "url": "https://madainproject.com/minaret_of_isa_(umayyad_mosque)",
        "classTags": []
      }
    ]
  },
  {
    "id": "links",
    "name": "Educational Links",
    "children": [
      {
        "id": "links_tools",
        "name": "Tools",
        "items": [
          {
            "id": "link_0_Family_Tree_of_the_Prophet_SA",
            "name": "Family Tree of the Prophet SA",
            "displayName": "Family Tree of the Prophet SA",
            "path": "https://www.familyecho.com/?p=START&c=xb2m6838f1r6wfot&f=528697926351751254&lang=en",
            "type": "link",
            "url": "https://www.familyecho.com/?p=START&c=xb2m6838f1r6wfot&f=528697926351751254&lang=en",
            "classTags": []
          },
          {
            "id": "link_1_Tahajjud_Time_Calculator",
            "name": "Tahajjud Time Calculator",
            "displayName": "Tahajjud Time Calculator",
            "path": "https://thirdofthenight.com",
            "type": "link",
            "url": "https://thirdofthenight.com",
            "classTags": []
          },
          {
            "id": "link_2_Life_of_Imam_Bukhari_Travels_and_Biography",
            "name": "Life of Imam Bukhari - Travels and Biography",
            "displayName": "Life of Imam Bukhari - Travels and Biography",
            "path": "https://map-bukhari-project.netlify.app",
            "type": "link",
            "url": "https://map-bukhari-project.netlify.app",
            "classTags": []
          },
          {
            "id": "link_3_PrayAir_Midflight_Prayer_Time_Calculator",
            "name": "PrayAir, Midflight Prayer Time Calculator",
            "displayName": "PrayAir, Midflight Prayer Time Calculator",
            "path": "https://prayair.app/",
            "type": "link",
            "url": "https://prayair.app/",
            "classTags": []
          },
          {
            "id": "link_4_Zakat_Calculator",
            "name": "Zakat Calculator",
            "displayName": "Zakat Calculator",
            "path": "https://islamic-relief.org/zakat-calculator/",
            "type": "link",
            "url": "https://islamic-relief.org/zakat-calculator/",
            "classTags": []
          }
        ]
      }
    ],
    "defaultCollapsed": true
  },
  {
    "id": "worksheets",
    "name": "Worksheets & Templates",
    "items": [
      {
        "id": "Classmate_Notes_Worksheets_and_templates_Surah_Baqarah_Tarjuma_Template_pdf",
        "name": "Surah Baqarah Tarjuma Template.pdf",
        "displayName": "Surah Baqarah Tarjuma Template",
        "path": "/batch4/Classmate_Notes/Worksheets_and_templates/Surah%20Baqarah%20Tarjuma%20Template.pdf",
        "type": "pdf"
      },
      {
        "id": "Classmate_Notes_Worksheets_and_templates_Verb_Scale_worksheet_Amayra_pdf",
        "name": "Verb Scale worksheet (Amayra)  .pdf",
        "displayName": "Verb Scale worksheet",
        "path": "/batch4/Classmate_Notes/Worksheets_and_templates/Verb%20Scale%20worksheet%20(Amayra)%20%20.pdf",
        "type": "pdf"
      }
    ],
    "defaultCollapsed": true
  },
  {
    "id": "practice",
    "name": "Practice & Exams",
    "items": [
      {
        "id": "Classmate_Notes_Comprehensive_Notes_Final_Seerah_Exam_Practice_Questions_Noor_pdf",
        "name": "Final Seerah Exam Practice Questions (Noor).pdf",
        "displayName": "Final Seerah Exam Practice Questions",
        "credit": "Noor",
        "path": "/batch4/Classmate_Notes/Comprehensive_Notes/Final%20Seerah%20Exam%20Practice%20Questions%20(Noor).pdf",
        "type": "pdf",
        "classTags": [
          "Seerah"
        ]
      },
      {
        "id": "Classmate_Notes_Worksheets_and_templates_Mock_Exam_Uloom_Al_Hadith_Answers_in_Amayra_pdf",
        "name": "Mock Exam Uloom Al Hadith - Answers in (Amayra).pdf",
        "displayName": "Mock Exam Uloom Al Hadith - Answers in",
        "credit": "Amayra",
        "path": "/batch4/Classmate_Notes/Worksheets_and_templates/Mock%20Exam%20Uloom%20Al%20Hadith%20-%20Answers%20in%20(Amayra).pdf",
        "type": "pdf"
      },
      {
        "id": "Classmate_Notes_Comprehensive_Notes_ANSWERS_Mock_Exam_Uloom_Al_Hadith_Amayra_pdf",
        "name": "ANSWERS Mock Exam Uloom Al Hadith (Amayra).pdf",
        "displayName": "Mock Exam Uloom Al Hadith Answers",
        "credit": "Amayra",
        "path": "/batch4/Classmate_Notes/Comprehensive_Notes/ANSWERS%20Mock%20Exam%20Uloom%20Al%20Hadith%20(Amayra).pdf",
        "type": "pdf",
        "classTags": [
          "Uloom Hadith"
        ]
      },
      {
        "id": "Classmate_Notes_Comprehensive_Notes_Seerah_Early_Madina_Exam_Study_Guide_Amayra_pdf",
        "name": "Seerah Early Madina Exam Study Guide (Amayra).pdf",
        "displayName": "Seerah Early Madina Exam Study Guide",
        "credit": "Amayra",
        "path": "/batch4/Classmate_Notes/Comprehensive_Notes/Seerah%20Early%20Madina%20Exam%20Study%20Guide%20(Amayra).pdf",
        "type": "pdf",
        "classTags": [
          "Seerah"
        ]
      },
      {
        "id": "Classmate_Notes_Comprehensive_Notes_Seerah_Mecca_Review_Notes_Aqsa_pdf",
        "name": "Seerah Mecca Review Notes (Aqsa).pdf",
        "displayName": "Seerah Mecca Review Notes",
        "credit": "Aqsa",
        "path": "/batch4/Classmate_Notes/Comprehensive_Notes/Seerah%20Mecca%20Review%20Notes%20(Aqsa).pdf",
        "type": "pdf",
        "classTags": [
          "Seerah"
        ]
      },
      {
        "id": "Classmate_Notes_Worksheets_and_templates_Worksheet_Uloom_Al_Hadith_Reference_Charts_lejla_pdf",
        "name": "Worksheet Uloom Al- Hadith Reference Charts (lejla).pdf",
        "displayName": "Worksheet Uloom Al- Hadith Reference Charts",
        "credit": "lejla",
        "path": "/batch4/Classmate_Notes/Worksheets_and_templates/Worksheet%20Uloom%20Al-%20Hadith%20Reference%20Charts%20(lejla).pdf",
        "type": "pdf"
      }
    ],
    "defaultCollapsed": true
  }
];

export const batch4Quicklinks: MediaSection[] = [
  {
    "id": "ql_morning_adhkaar_tools",
    "name": "Morning Adhkaar + Tools",
    "items": [
      {
        "id": "Classmate_Notes_Official_notes_or_Book_pdfs_Morning_Adhkaar_Amanah_Fitness_pdf",
        "name": "Morning Adhkaar Amanah Fitness.pdf",
        "displayName": "Morning Adhkaar",
        "path": "/batch4/Classmate_Notes/Official_notes_or_Book_pdfs/Morning%20Adhkaar%20Amanah%20Fitness.pdf",
        "type": "pdf"
      },
      {
        "id": "link_1_Tahajjud_Time_Calculator",
        "name": "Tahajjud Time Calculator",
        "displayName": "Tahajjud Time Calculator",
        "path": "https://thirdofthenight.com",
        "type": "link",
        "url": "https://thirdofthenight.com",
        "classTags": []
      },
      {
        "id": "link_2_Sentence_Generator_Arhum_",
        "name": "Sentence Generator (Arhum)",
        "displayName": "Sentence Generator",
        "credit": "Arhum",
        "path": "https://chatgpt.com/g/g-68fa247cbe988191b5da9c3de3dedfc3-arabic-sentence-generator-miftaah-seekers",
        "type": "link",
        "url": "https://chatgpt.com/g/g-68fa247cbe988191b5da9c3de3dedfc3-arabic-sentence-generator-miftaah-seekers",
        "classTags": []
      },
      {
        "id": "link_4_Sarf_Word_Practice_Generator",
        "name": "Sarf Word Practice Generator",
        "displayName": "Sarf Word Practice Generator",
        "path": "https://sarfing.app",
        "type": "link",
        "url": "https://sarfing.app",
        "classTags": []
      },
      {
        "id": "link_5_PrayAir_Midflight_Prayer_Time_Calculator",
        "name": "PrayAir, Midflight Prayer Time Calculator",
        "displayName": "PrayAir, Midflight Prayer Time Calculator",
        "path": "https://prayair.app/",
        "type": "link",
        "url": "https://prayair.app/",
        "classTags": []
      },
      {
        "id": "link_6_Zakat_Calculator",
        "name": "Zakat Calculator",
        "displayName": "Zakat Calculator",
        "path": "https://islamic-relief.org/zakat-calculator/",
        "type": "link",
        "url": "https://islamic-relief.org/zakat-calculator/",
        "classTags": []
      }
    ]
  },
  {
    "id": "ql_worksheets",
    "name": "Worksheets",
    "items": [
      {
        "id": "Classmate_Notes_Worksheets_and_templates_Surah_Baqarah_Tarjuma_Template_pdf",
        "name": "Surah Baqarah Tarjuma Template.pdf",
        "displayName": "Surah Baqarah Tarjuma Template",
        "path": "/batch4/Classmate_Notes/Worksheets_and_templates/Surah%20Baqarah%20Tarjuma%20Template.pdf",
        "type": "pdf"
      },
      {
        "id": "Classmate_Notes_Worksheets_and_templates_Verb_Scale_worksheet_Amayra_pdf",
        "name": "Verb Scale worksheet (Amayra)  .pdf",
        "displayName": "Verb Scale worksheet",
        "path": "/batch4/Classmate_Notes/Worksheets_and_templates/Verb%20Scale%20worksheet%20(Amayra)%20%20.pdf",
        "type": "pdf"
      }
    ]
  },
  {
    "id": "ql_quizlets",
    "name": "Quizlets",
    "items": [
      {
        "id": "link_100_Arabic_Vocabulary_Quizlet_Miski_",
        "name": "Arabic Vocabulary Quizlet (Miski)",
        "displayName": "Arabic Vocabulary Quizlet",
        "credit": "Miski",
        "path": "https://quizlet.com/1077642316/arabic-vocabulary-flash-cards/?i=3s0dgi&x=1jqY",
        "type": "link",
        "url": "https://quizlet.com/1077642316/arabic-vocabulary-flash-cards/?i=3s0dgi&x=1jqY",
        "classTags": []
      },
      {
        "id": "link_101_Arabic_Sarf_Vocab_Set_Sarf_Part_2_Arhum_",
        "name": "Arabic Sarf Vocab Set - Sarf Part 2 (Arhum)",
        "displayName": "Arabic Sarf Vocab Set - Sarf Part 2",
        "credit": "Arhum",
        "path": "https://quizlet.com/1070870221/vocab-set-2-sarf-section-flash-cards/?i=6qeu4n&x=1jqY",
        "type": "link",
        "url": "https://quizlet.com/1070870221/vocab-set-2-sarf-section-flash-cards/?i=6qeu4n&x=1jqY",
        "classTags": []
      },
      {
        "id": "link_102_Arabic_Sarf_Vocab_Set_Sarf_Part_2",
        "name": "Arabic Sarf Vocab Set - Sarf Part 2",
        "displayName": "Arabic Sarf Vocab Set - Sarf Part 2",
        "path": "https://quizlet.com/1095134612/sarf-vocab-set-1-flash-cards/?i=6saqto&x=1jqY",
        "type": "link",
        "url": "https://quizlet.com/1095134612/sarf-vocab-set-1-flash-cards/?i=6saqto&x=1jqY",
        "classTags": []
      },
      {
        "id": "link_103_Quizlet_for_Uloom_Hadith_Terminology_Aqsa_",
        "name": "Quizlet for Uloom Hadith Terminology (Aqsa)",
        "displayName": "Quizlet for Uloom Hadith Terminology",
        "credit": "Aqsa",
        "path": "https://quizlet.com/845936651/uloom-al-hadith-flash-cards/?i=5zwu9x&x=1jqY",
        "type": "link",
        "url": "https://quizlet.com/845936651/uloom-al-hadith-flash-cards/?i=5zwu9x&x=1jqY",
        "classTags": []
      },
      {
        "id": "link_104_Canva_Flashcards_for_Uloom_Al_Hadith_Yasmine_",
        "name": "Canva Flashcards for Uloom Al-Hadith (Yasmine)",
        "displayName": "Canva Flashcards for Uloom Al-Hadith",
        "credit": "Yasmine",
        "path": "https://www.canva.com/design/DAG68OVEdNg/K6ABExtWiP3ifWQcRCTxJg/view?utm_content=DAG68OVEdNg&utm_campaign=designshare&utm_medium=link2&utm_source=uniquelinks&utlId=ha289dd50a3#1",
        "type": "link",
        "url": "https://www.canva.com/design/DAG68OVEdNg/K6ABExtWiP3ifWQcRCTxJg/view?utm_content=DAG68OVEdNg&utm_campaign=designshare&utm_medium=link2&utm_source=uniquelinks&utlId=ha289dd50a3#1",
        "classTags": []
      }
    ]
  },
  {
    "id": "ql_practice",
    "name": "Practice & Exams",
    "items": [
      {
        "id": "Classmate_Notes_Comprehensive_Notes_Final_Seerah_Exam_Practice_Questions_Noor_pdf",
        "name": "Final Seerah Exam Practice Questions (Noor).pdf",
        "displayName": "Final Seerah Exam Practice Questions",
        "credit": "Noor",
        "path": "/batch4/Classmate_Notes/Comprehensive_Notes/Final%20Seerah%20Exam%20Practice%20Questions%20(Noor).pdf",
        "type": "pdf",
        "classTags": [
          "Seerah"
        ]
      },
      {
        "id": "Classmate_Notes_Worksheets_and_templates_Mock_Exam_Uloom_Al_Hadith_Answers_in_Amayra_pdf",
        "name": "Mock Exam Uloom Al Hadith - Answers in (Amayra).pdf",
        "displayName": "Mock Exam Uloom Al Hadith - Answers in",
        "credit": "Amayra",
        "path": "/batch4/Classmate_Notes/Worksheets_and_templates/Mock%20Exam%20Uloom%20Al%20Hadith%20-%20Answers%20in%20(Amayra).pdf",
        "type": "pdf"
      },
      {
        "id": "Classmate_Notes_Comprehensive_Notes_ANSWERS_Mock_Exam_Uloom_Al_Hadith_Amayra_pdf",
        "name": "ANSWERS Mock Exam Uloom Al Hadith (Amayra).pdf",
        "displayName": "Mock Exam Uloom Al Hadith Answers",
        "credit": "Amayra",
        "path": "/batch4/Classmate_Notes/Comprehensive_Notes/ANSWERS%20Mock%20Exam%20Uloom%20Al%20Hadith%20(Amayra).pdf",
        "type": "pdf",
        "classTags": [
          "Uloom Hadith"
        ]
      }
    ]
  }
];

export const DUAS_GALLERY_ID = '__duas_gallery__';

export const batch4Duas: MediaItem[] = [
  {
    "id": "Classmate_Notes_Duas_from_Seerah_05bf0398_22fd_4095_8a63_adcc81bcd5e8_JPG",
    "name": "05bf0398-22fd-4095-8a63-adcc81bcd5e8.JPG",
    "displayName": "05bf0398-22fd-4095-8a63-adcc81bcd5e8",
    "path": "/batch4/Classmate_Notes/Duas_from_Seerah/05bf0398-22fd-4095-8a63-adcc81bcd5e8.JPG",
    "type": "image",
    "classTags": [
      "Seerah"
    ],
    "description": ""
  },
  {
    "id": "Classmate_Notes_Duas_from_Seerah_085c73c4_f0bc_486b_b894_2ca8f3dd5008_JPG",
    "name": "085c73c4-f0bc-486b-b894-2ca8f3dd5008.JPG",
    "displayName": "085c73c4-f0bc-486b-b894-2ca8f3dd5008",
    "path": "/batch4/Classmate_Notes/Duas_from_Seerah/085c73c4-f0bc-486b-b894-2ca8f3dd5008.JPG",
    "type": "image",
    "classTags": [
      "Seerah"
    ],
    "description": ""
  },
  {
    "id": "Classmate_Notes_Duas_from_Seerah_164dd666_1d27_4ee5_8518_2e005db702f9_JPG",
    "name": "164dd666-1d27-4ee5-8518-2e005db702f9.JPG",
    "displayName": "164dd666-1d27-4ee5-8518-2e005db702f9",
    "path": "/batch4/Classmate_Notes/Duas_from_Seerah/164dd666-1d27-4ee5-8518-2e005db702f9.JPG",
    "type": "image",
    "classTags": [
      "Seerah"
    ],
    "description": ""
  },
  {
    "id": "Classmate_Notes_Duas_from_Seerah_1a41c972_dc73_438f_99b6_afc2cffa3b08_JPG",
    "name": "1a41c972-dc73-438f-99b6-afc2cffa3b08.JPG",
    "displayName": "1a41c972-dc73-438f-99b6-afc2cffa3b08",
    "path": "/batch4/Classmate_Notes/Duas_from_Seerah/1a41c972-dc73-438f-99b6-afc2cffa3b08.JPG",
    "type": "image",
    "classTags": [
      "Seerah"
    ],
    "description": ""
  },
  {
    "id": "Classmate_Notes_Duas_from_Seerah_1b948a14_69dd_4b06_b9cd_b30d53445fb6_JPG",
    "name": "1b948a14-69dd-4b06-b9cd-b30d53445fb6.JPG",
    "displayName": "1b948a14-69dd-4b06-b9cd-b30d53445fb6",
    "path": "/batch4/Classmate_Notes/Duas_from_Seerah/1b948a14-69dd-4b06-b9cd-b30d53445fb6.JPG",
    "type": "image",
    "classTags": [
      "Seerah"
    ],
    "description": ""
  },
  {
    "id": "Classmate_Notes_Duas_from_Seerah_1f729938_9547_462d_9fd7_62e83d098cf2_JPG",
    "name": "1f729938-9547-462d-9fd7-62e83d098cf2.JPG",
    "displayName": "1f729938-9547-462d-9fd7-62e83d098cf2",
    "path": "/batch4/Classmate_Notes/Duas_from_Seerah/1f729938-9547-462d-9fd7-62e83d098cf2.JPG",
    "type": "image",
    "classTags": [
      "Seerah"
    ],
    "description": ""
  },
  {
    "id": "Classmate_Notes_Duas_from_Seerah_28c00f15_66bd_4368_b145_fb496a28b7be_JPG",
    "name": "28c00f15-66bd-4368-b145-fb496a28b7be.JPG",
    "displayName": "28c00f15-66bd-4368-b145-fb496a28b7be",
    "path": "/batch4/Classmate_Notes/Duas_from_Seerah/28c00f15-66bd-4368-b145-fb496a28b7be.JPG",
    "type": "image",
    "classTags": [
      "Seerah"
    ],
    "description": ""
  },
  {
    "id": "Classmate_Notes_Duas_from_Seerah_320c080d_87a2_4e8a_8fcb_9ebf352db0d8_JPG",
    "name": "320c080d-87a2-4e8a-8fcb-9ebf352db0d8.JPG",
    "displayName": "320c080d-87a2-4e8a-8fcb-9ebf352db0d8",
    "path": "/batch4/Classmate_Notes/Duas_from_Seerah/320c080d-87a2-4e8a-8fcb-9ebf352db0d8.JPG",
    "type": "image",
    "classTags": [
      "Seerah"
    ],
    "description": ""
  },
  {
    "id": "Classmate_Notes_Duas_from_Seerah_3a6129fa_4860_440f_bbd7_79545c2b2c9a_JPG",
    "name": "3a6129fa-4860-440f-bbd7-79545c2b2c9a.JPG",
    "displayName": "3a6129fa-4860-440f-bbd7-79545c2b2c9a",
    "path": "/batch4/Classmate_Notes/Duas_from_Seerah/3a6129fa-4860-440f-bbd7-79545c2b2c9a.JPG",
    "type": "image",
    "classTags": [
      "Seerah"
    ],
    "description": ""
  },
  {
    "id": "Classmate_Notes_Duas_from_Seerah_56d1255d_94b9_4e87_b052_255b03b30485_JPG",
    "name": "56d1255d-94b9-4e87-b052-255b03b30485.JPG",
    "displayName": "56d1255d-94b9-4e87-b052-255b03b30485",
    "path": "/batch4/Classmate_Notes/Duas_from_Seerah/56d1255d-94b9-4e87-b052-255b03b30485.JPG",
    "type": "image",
    "classTags": [
      "Seerah"
    ],
    "description": ""
  },
  {
    "id": "Classmate_Notes_Duas_from_Seerah_63082ef7_b216_4414_b686_ebaefb4d4f13_JPG",
    "name": "63082ef7-b216-4414-b686-ebaefb4d4f13.JPG",
    "displayName": "63082ef7-b216-4414-b686-ebaefb4d4f13",
    "path": "/batch4/Classmate_Notes/Duas_from_Seerah/63082ef7-b216-4414-b686-ebaefb4d4f13.JPG",
    "type": "image",
    "classTags": [
      "Seerah"
    ],
    "description": ""
  },
  {
    "id": "Classmate_Notes_Duas_from_Seerah_6c4b9777_2785_41fa_8ff0_4b021bd20029_JPG",
    "name": "6c4b9777-2785-41fa-8ff0-4b021bd20029.JPG",
    "displayName": "6c4b9777-2785-41fa-8ff0-4b021bd20029",
    "path": "/batch4/Classmate_Notes/Duas_from_Seerah/6c4b9777-2785-41fa-8ff0-4b021bd20029.JPG",
    "type": "image",
    "classTags": [
      "Seerah"
    ],
    "description": ""
  },
  {
    "id": "Classmate_Notes_Duas_from_Seerah_6cc94753_2259_4b52_93ff_dc276dade014_JPG",
    "name": "6cc94753-2259-4b52-93ff-dc276dade014.JPG",
    "displayName": "6cc94753-2259-4b52-93ff-dc276dade014",
    "path": "/batch4/Classmate_Notes/Duas_from_Seerah/6cc94753-2259-4b52-93ff-dc276dade014.JPG",
    "type": "image",
    "classTags": [
      "Seerah"
    ],
    "description": ""
  },
  {
    "id": "Classmate_Notes_Duas_from_Seerah_7639db8a_56cd_4053_9cad_e997ca7ddcd9_JPG",
    "name": "7639db8a-56cd-4053-9cad-e997ca7ddcd9.JPG",
    "displayName": "7639db8a-56cd-4053-9cad-e997ca7ddcd9",
    "path": "/batch4/Classmate_Notes/Duas_from_Seerah/7639db8a-56cd-4053-9cad-e997ca7ddcd9.JPG",
    "type": "image",
    "classTags": [
      "Seerah"
    ],
    "description": ""
  },
  {
    "id": "Classmate_Notes_Duas_from_Seerah_7c760e20_ec70_414e_b24f_e6471051322e_JPG",
    "name": "7c760e20-ec70-414e-b24f-e6471051322e.JPG",
    "displayName": "7c760e20-ec70-414e-b24f-e6471051322e",
    "path": "/batch4/Classmate_Notes/Duas_from_Seerah/7c760e20-ec70-414e-b24f-e6471051322e.JPG",
    "type": "image",
    "classTags": [
      "Seerah"
    ],
    "description": ""
  },
  {
    "id": "Classmate_Notes_Duas_from_Seerah_80fec1c5_a533_4a83_ae5f_a013b1881b7f_JPG",
    "name": "80fec1c5-a533-4a83-ae5f-a013b1881b7f.JPG",
    "displayName": "80fec1c5-a533-4a83-ae5f-a013b1881b7f",
    "path": "/batch4/Classmate_Notes/Duas_from_Seerah/80fec1c5-a533-4a83-ae5f-a013b1881b7f.JPG",
    "type": "image",
    "classTags": [
      "Seerah"
    ],
    "description": ""
  },
  {
    "id": "Classmate_Notes_Duas_from_Seerah_Dua_for_Wudhu_pdf",
    "name": "Dua_for_Wudhu.pdf",
    "displayName": "Dua for Wudhu",
    "path": "/batch4/Classmate_Notes/Duas_from_Seerah/Dua_for_Wudhu.pdf",
    "type": "pdf",
    "classTags": [
      "Seerah"
    ],
    "description": ""
  },
  {
    "id": "Classmate_Notes_Duas_from_Seerah_Dua_for_clear_vision_JPG",
    "name": "Dua_for_clear_vision.JPG",
    "displayName": "Dua for clear vision",
    "path": "/batch4/Classmate_Notes/Duas_from_Seerah/Dua_for_clear_vision.JPG",
    "type": "image",
    "classTags": [
      "Seerah"
    ],
    "description": ""
  },
  {
    "id": "Classmate_Notes_Duas_from_Seerah_aa54f3c1_691e_44a3_b8a2_ce1d10426d84_JPG",
    "name": "aa54f3c1-691e-44a3-b8a2-ce1d10426d84.JPG",
    "displayName": "aa54f3c1-691e-44a3-b8a2-ce1d10426d84",
    "path": "/batch4/Classmate_Notes/Duas_from_Seerah/aa54f3c1-691e-44a3-b8a2-ce1d10426d84.JPG",
    "type": "image",
    "classTags": [
      "Seerah"
    ],
    "description": ""
  },
  {
    "id": "Classmate_Notes_Duas_from_Seerah_b3aa548d_44e6_4ec6_95d8_788755e747cd_JPG",
    "name": "b3aa548d-44e6-4ec6-95d8-788755e747cd.JPG",
    "displayName": "b3aa548d-44e6-4ec6-95d8-788755e747cd",
    "path": "/batch4/Classmate_Notes/Duas_from_Seerah/b3aa548d-44e6-4ec6-95d8-788755e747cd.JPG",
    "type": "image",
    "classTags": [
      "Seerah"
    ],
    "description": ""
  },
  {
    "id": "Classmate_Notes_Duas_from_Seerah_c199ff46_ace9_4a89_812c_f7c0bfdc8ee3_JPG",
    "name": "c199ff46-ace9-4a89-812c-f7c0bfdc8ee3.JPG",
    "displayName": "c199ff46-ace9-4a89-812c-f7c0bfdc8ee3",
    "path": "/batch4/Classmate_Notes/Duas_from_Seerah/c199ff46-ace9-4a89-812c-f7c0bfdc8ee3.JPG",
    "type": "image",
    "classTags": [
      "Seerah"
    ],
    "description": ""
  },
  {
    "id": "Classmate_Notes_Duas_from_Seerah_c908ee85_ebe6_4b61_b1ee_f3ba9f4cc294_JPG",
    "name": "c908ee85-ebe6-4b61-b1ee-f3ba9f4cc294.JPG",
    "displayName": "c908ee85-ebe6-4b61-b1ee-f3ba9f4cc294",
    "path": "/batch4/Classmate_Notes/Duas_from_Seerah/c908ee85-ebe6-4b61-b1ee-f3ba9f4cc294.JPG",
    "type": "image",
    "classTags": [
      "Seerah"
    ],
    "description": ""
  },
  {
    "id": "Classmate_Notes_Duas_from_Seerah_ccc2a7ea_092f_4a70_8640_9760c0b2cf7d_JPG",
    "name": "ccc2a7ea-092f-4a70-8640-9760c0b2cf7d.JPG",
    "displayName": "ccc2a7ea-092f-4a70-8640-9760c0b2cf7d",
    "path": "/batch4/Classmate_Notes/Duas_from_Seerah/ccc2a7ea-092f-4a70-8640-9760c0b2cf7d.JPG",
    "type": "image",
    "classTags": [
      "Seerah"
    ],
    "description": ""
  },
  {
    "id": "Classmate_Notes_Duas_from_Seerah_d28356ad_3f5b_4546_b08c_a8aebab7931f_JPG",
    "name": "d28356ad-3f5b-4546-b08c-a8aebab7931f.JPG",
    "displayName": "d28356ad-3f5b-4546-b08c-a8aebab7931f",
    "path": "/batch4/Classmate_Notes/Duas_from_Seerah/d28356ad-3f5b-4546-b08c-a8aebab7931f.JPG",
    "type": "image",
    "classTags": [
      "Seerah"
    ],
    "description": ""
  },
  {
    "id": "Classmate_Notes_Duas_from_Seerah_d6374068_27db_48fc_8163_18aeb9fa9ccd_JPG",
    "name": "d6374068-27db-48fc-8163-18aeb9fa9ccd.JPG",
    "displayName": "d6374068-27db-48fc-8163-18aeb9fa9ccd",
    "path": "/batch4/Classmate_Notes/Duas_from_Seerah/d6374068-27db-48fc-8163-18aeb9fa9ccd.JPG",
    "type": "image",
    "classTags": [
      "Seerah"
    ],
    "description": ""
  },
  {
    "id": "Classmate_Notes_Duas_from_Seerah_e7fc09ca_ba9f_4e2b_950e_800cc41f3e7f_JPG",
    "name": "e7fc09ca-ba9f-4e2b-950e-800cc41f3e7f.JPG",
    "displayName": "e7fc09ca-ba9f-4e2b-950e-800cc41f3e7f",
    "path": "/batch4/Classmate_Notes/Duas_from_Seerah/e7fc09ca-ba9f-4e2b-950e-800cc41f3e7f.JPG",
    "type": "image",
    "classTags": [
      "Seerah"
    ],
    "description": ""
  },
  {
    "id": "Classmate_Notes_Duas_from_Seerah_f29a0671_1507_425a_8ec8_ae5b9b347165_JPG",
    "name": "f29a0671-1507-425a-8ec8-ae5b9b347165.JPG",
    "displayName": "f29a0671-1507-425a-8ec8-ae5b9b347165",
    "path": "/batch4/Classmate_Notes/Duas_from_Seerah/f29a0671-1507-425a-8ec8-ae5b9b347165.JPG",
    "type": "image",
    "classTags": [
      "Seerah"
    ],
    "description": ""
  },
  {
    "id": "Classmate_Notes_Duas_from_Seerah_f6874a1a_f2d9_4010_b118_5ac7859fb50f_JPG",
    "name": "f6874a1a-f2d9-4010-b118-5ac7859fb50f.JPG",
    "displayName": "f6874a1a-f2d9-4010-b118-5ac7859fb50f",
    "path": "/batch4/Classmate_Notes/Duas_from_Seerah/f6874a1a-f2d9-4010-b118-5ac7859fb50f.JPG",
    "type": "image",
    "classTags": [
      "Seerah"
    ],
    "description": ""
  }
];
